# Generated by Django 4.1.7 on 2023-02-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolidApi', '0002_alter_events_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='sensor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
