# Generated by Django 4.1.7 on 2023-02-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolidApi', '0003_alter_events_humidity_alter_events_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='events',
            name='sensor_id',
            field=models.IntegerField(),
        ),
    ]
