# Generated by Django 4.1.7 on 2023-02-16 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolidApi', '0004_alter_events_name_alter_events_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='sensor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bolidApi.sensors'),
        ),
    ]
