# Generated by Django 4.1.7 on 2023-02-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolidApi', '0006_alter_sensors_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='type',
            field=models.CharField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')], max_length=255),
        ),
    ]
