# Generated by Django 4.1.7 on 2023-02-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolidApi', '0007_alter_sensors_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='type',
            field=models.CharField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], max_length=255),
        ),
    ]
