# Generated by Django 4.1.7 on 2023-02-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolidApi', '0008_alter_sensors_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='type',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], max_length=255),
        ),
    ]
