# Generated by Django 4.1.7 on 2023-02-17 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolidApi', '0010_alter_sensors_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolidApi.sensors'),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='type',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
    ]
