# Generated by Django 4.1.7 on 2023-02-20 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolidApi', '0012_alter_events_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='humidity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
