version: "3.1"
services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123321987sfSGsh
      - POSTGRES_DB=bolid
      - POSTGRES_PORT=5432
    ports:
      - "5342:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  pgadmin:
      image: dpage/pgadmin4
      depends_on:
        - db
      ports:
        - "5051:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      restart: always

  web:
      working_dir: /bolid/bolid/
      volumes:
        - .:/bolid
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      ports:
        - "8000:8000"
      env_file:
        - ./bolid/.env
      depends_on:
        - db
volumes:
  static:
  media:
  postgres_data:

